# Generated by Django 3.1.12 on 2022-10-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_calories', models.IntegerField(default=0)),
                ('ingredients', models.CharField(blank=True, max_length=10000, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('food_picture', models.ImageField(upload_to='food_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
